// Code generated by protoc-gen-go.
// source: steammessages_remoteclient.proto
// DO NOT EDIT!

/*
Package steammessages_remoteclient is a generated protocol buffer package.

It is generated from these files:
	steammessages_remoteclient.proto

It has these top-level messages:
	CMsgRemoteClientBroadcastHeader
	CMsgRemoteClientBroadcastStatus
	CMsgRemoteClientBroadcastDiscovery
	CMsgRemoteClientAppStatus
	CMsgRemoteClientAuth
	CMsgRemoteClientAuthResponse
	CMsgRemoteClientStartStream
	CMsgRemoteClientStartStreamResponse
	CMsgRemoteClientPing
	CMsgRemoteClientPingResponse
	CMsgRemoteClientAcceptEULA
	CMsgRemoteClientGetControllerConfig
	CMsgRemoteClientGetControllerConfigResponse
*/
package internal

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// discarding unused import steammessages_base "steammessages_base.pb"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type ERemoteClientBroadcastMsg int32

const (
	ERemoteClientBroadcastMsg_k_ERemoteClientBroadcastMsgDiscovery ERemoteClientBroadcastMsg = 0
	ERemoteClientBroadcastMsg_k_ERemoteClientBroadcastMsgStatus    ERemoteClientBroadcastMsg = 1
	ERemoteClientBroadcastMsg_k_ERemoteClientBroadcastMsgOffline   ERemoteClientBroadcastMsg = 2
)

var ERemoteClientBroadcastMsg_name = map[int32]string{
	0: "k_ERemoteClientBroadcastMsgDiscovery",
	1: "k_ERemoteClientBroadcastMsgStatus",
	2: "k_ERemoteClientBroadcastMsgOffline",
}
var ERemoteClientBroadcastMsg_value = map[string]int32{
	"k_ERemoteClientBroadcastMsgDiscovery": 0,
	"k_ERemoteClientBroadcastMsgStatus":    1,
	"k_ERemoteClientBroadcastMsgOffline":   2,
}

func (x ERemoteClientBroadcastMsg) Enum() *ERemoteClientBroadcastMsg {
	p := new(ERemoteClientBroadcastMsg)
	*p = x
	return p
}
func (x ERemoteClientBroadcastMsg) String() string {
	return proto.EnumName(ERemoteClientBroadcastMsg_name, int32(x))
}
func (x *ERemoteClientBroadcastMsg) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ERemoteClientBroadcastMsg_value, data, "ERemoteClientBroadcastMsg")
	if err != nil {
		return err
	}
	*x = ERemoteClientBroadcastMsg(value)
	return nil
}

type ERemoteClientService int32

const (
	ERemoteClientService_k_ERemoteClientServiceNone          ERemoteClientService = 0
	ERemoteClientService_k_ERemoteClientServiceRemoteControl ERemoteClientService = 1
)

var ERemoteClientService_name = map[int32]string{
	0: "k_ERemoteClientServiceNone",
	1: "k_ERemoteClientServiceRemoteControl",
}
var ERemoteClientService_value = map[string]int32{
	"k_ERemoteClientServiceNone":          0,
	"k_ERemoteClientServiceRemoteControl": 1,
}

func (x ERemoteClientService) Enum() *ERemoteClientService {
	p := new(ERemoteClientService)
	*p = x
	return p
}
func (x ERemoteClientService) String() string {
	return proto.EnumName(ERemoteClientService_name, int32(x))
}
func (x *ERemoteClientService) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ERemoteClientService_value, data, "ERemoteClientService")
	if err != nil {
		return err
	}
	*x = ERemoteClientService(value)
	return nil
}

type CMsgRemoteClientBroadcastHeader struct {
	ClientId         *uint64                    `protobuf:"varint,1,opt,name=client_id" json:"client_id,omitempty"`
	MsgType          *ERemoteClientBroadcastMsg `protobuf:"varint,2,opt,name=msg_type,enum=ERemoteClientBroadcastMsg,def=0" json:"msg_type,omitempty"`
	XXX_unrecognized []byte                     `json:"-"`
}

func (m *CMsgRemoteClientBroadcastHeader) Reset()         { *m = CMsgRemoteClientBroadcastHeader{} }
func (m *CMsgRemoteClientBroadcastHeader) String() string { return proto.CompactTextString(m) }
func (*CMsgRemoteClientBroadcastHeader) ProtoMessage()    {}

const Default_CMsgRemoteClientBroadcastHeader_MsgType ERemoteClientBroadcastMsg = ERemoteClientBroadcastMsg_k_ERemoteClientBroadcastMsgDiscovery

func (m *CMsgRemoteClientBroadcastHeader) GetClientId() uint64 {
	if m != nil && m.ClientId != nil {
		return *m.ClientId
	}
	return 0
}

func (m *CMsgRemoteClientBroadcastHeader) GetMsgType() ERemoteClientBroadcastMsg {
	if m != nil && m.MsgType != nil {
		return *m.MsgType
	}
	return Default_CMsgRemoteClientBroadcastHeader_MsgType
}

type CMsgRemoteClientBroadcastStatus struct {
	Version           *int32                                  `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	MinVersion        *int32                                  `protobuf:"varint,2,opt,name=min_version" json:"min_version,omitempty"`
	ConnectPort       *uint32                                 `protobuf:"varint,3,opt,name=connect_port" json:"connect_port,omitempty"`
	Hostname          *string                                 `protobuf:"bytes,4,opt,name=hostname" json:"hostname,omitempty"`
	EnabledServices   *uint32                                 `protobuf:"varint,6,opt,name=enabled_services" json:"enabled_services,omitempty"`
	Ostype            *int32                                  `protobuf:"varint,7,opt,name=ostype,def=0" json:"ostype,omitempty"`
	Is64Bit           *bool                                   `protobuf:"varint,8,opt,name=is64bit,def=0" json:"is64bit,omitempty"`
	Users             []*CMsgRemoteClientBroadcastStatus_User `protobuf:"bytes,9,rep,name=users" json:"users,omitempty"`
	RemoteControlPort *uint32                                 `protobuf:"varint,10,opt,name=remote_control_port" json:"remote_control_port,omitempty"`
	XXX_unrecognized  []byte                                  `json:"-"`
}

func (m *CMsgRemoteClientBroadcastStatus) Reset()         { *m = CMsgRemoteClientBroadcastStatus{} }
func (m *CMsgRemoteClientBroadcastStatus) String() string { return proto.CompactTextString(m) }
func (*CMsgRemoteClientBroadcastStatus) ProtoMessage()    {}

const Default_CMsgRemoteClientBroadcastStatus_Ostype int32 = 0
const Default_CMsgRemoteClientBroadcastStatus_Is64Bit bool = false

func (m *CMsgRemoteClientBroadcastStatus) GetVersion() int32 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *CMsgRemoteClientBroadcastStatus) GetMinVersion() int32 {
	if m != nil && m.MinVersion != nil {
		return *m.MinVersion
	}
	return 0
}

func (m *CMsgRemoteClientBroadcastStatus) GetConnectPort() uint32 {
	if m != nil && m.ConnectPort != nil {
		return *m.ConnectPort
	}
	return 0
}

func (m *CMsgRemoteClientBroadcastStatus) GetHostname() string {
	if m != nil && m.Hostname != nil {
		return *m.Hostname
	}
	return ""
}

func (m *CMsgRemoteClientBroadcastStatus) GetEnabledServices() uint32 {
	if m != nil && m.EnabledServices != nil {
		return *m.EnabledServices
	}
	return 0
}

func (m *CMsgRemoteClientBroadcastStatus) GetOstype() int32 {
	if m != nil && m.Ostype != nil {
		return *m.Ostype
	}
	return Default_CMsgRemoteClientBroadcastStatus_Ostype
}

func (m *CMsgRemoteClientBroadcastStatus) GetIs64Bit() bool {
	if m != nil && m.Is64Bit != nil {
		return *m.Is64Bit
	}
	return Default_CMsgRemoteClientBroadcastStatus_Is64Bit
}

func (m *CMsgRemoteClientBroadcastStatus) GetUsers() []*CMsgRemoteClientBroadcastStatus_User {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *CMsgRemoteClientBroadcastStatus) GetRemoteControlPort() uint32 {
	if m != nil && m.RemoteControlPort != nil {
		return *m.RemoteControlPort
	}
	return 0
}

type CMsgRemoteClientBroadcastStatus_User struct {
	Steamid          *uint64 `protobuf:"fixed64,1,opt,name=steamid" json:"steamid,omitempty"`
	AuthKeyId        *uint32 `protobuf:"varint,2,opt,name=auth_key_id" json:"auth_key_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CMsgRemoteClientBroadcastStatus_User) Reset()         { *m = CMsgRemoteClientBroadcastStatus_User{} }
func (m *CMsgRemoteClientBroadcastStatus_User) String() string { return proto.CompactTextString(m) }
func (*CMsgRemoteClientBroadcastStatus_User) ProtoMessage()    {}

func (m *CMsgRemoteClientBroadcastStatus_User) GetSteamid() uint64 {
	if m != nil && m.Steamid != nil {
		return *m.Steamid
	}
	return 0
}

func (m *CMsgRemoteClientBroadcastStatus_User) GetAuthKeyId() uint32 {
	if m != nil && m.AuthKeyId != nil {
		return *m.AuthKeyId
	}
	return 0
}

type CMsgRemoteClientBroadcastDiscovery struct {
	SeqNum           *uint32 `protobuf:"varint,1,opt,name=seq_num" json:"seq_num,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CMsgRemoteClientBroadcastDiscovery) Reset()         { *m = CMsgRemoteClientBroadcastDiscovery{} }
func (m *CMsgRemoteClientBroadcastDiscovery) String() string { return proto.CompactTextString(m) }
func (*CMsgRemoteClientBroadcastDiscovery) ProtoMessage()    {}

func (m *CMsgRemoteClientBroadcastDiscovery) GetSeqNum() uint32 {
	if m != nil && m.SeqNum != nil {
		return *m.SeqNum
	}
	return 0
}

type CMsgRemoteClientAppStatus struct {
	StatusUpdates    []*CMsgRemoteClientAppStatus_AppStatus `protobuf:"bytes,1,rep,name=status_updates" json:"status_updates,omitempty"`
	XXX_unrecognized []byte                                 `json:"-"`
}

func (m *CMsgRemoteClientAppStatus) Reset()         { *m = CMsgRemoteClientAppStatus{} }
func (m *CMsgRemoteClientAppStatus) String() string { return proto.CompactTextString(m) }
func (*CMsgRemoteClientAppStatus) ProtoMessage()    {}

func (m *CMsgRemoteClientAppStatus) GetStatusUpdates() []*CMsgRemoteClientAppStatus_AppStatus {
	if m != nil {
		return m.StatusUpdates
	}
	return nil
}

type CMsgRemoteClientAppStatus_AppUpdateInfo struct {
	TimeUpdateStart           *uint32 `protobuf:"fixed32,1,opt,name=time_update_start" json:"time_update_start,omitempty"`
	BytesToDownload           *uint64 `protobuf:"varint,2,opt,name=bytes_to_download" json:"bytes_to_download,omitempty"`
	BytesDownloaded           *uint64 `protobuf:"varint,3,opt,name=bytes_downloaded" json:"bytes_downloaded,omitempty"`
	BytesToProcess            *uint64 `protobuf:"varint,4,opt,name=bytes_to_process" json:"bytes_to_process,omitempty"`
	BytesProcessed            *uint64 `protobuf:"varint,5,opt,name=bytes_processed" json:"bytes_processed,omitempty"`
	EstimatedSecondsRemaining *int32  `protobuf:"varint,6,opt,name=estimated_seconds_remaining,def=-1" json:"estimated_seconds_remaining,omitempty"`
	UpdateResult              *int32  `protobuf:"varint,7,opt,name=update_result" json:"update_result,omitempty"`
	XXX_unrecognized          []byte  `json:"-"`
}

func (m *CMsgRemoteClientAppStatus_AppUpdateInfo) Reset() {
	*m = CMsgRemoteClientAppStatus_AppUpdateInfo{}
}
func (m *CMsgRemoteClientAppStatus_AppUpdateInfo) String() string { return proto.CompactTextString(m) }
func (*CMsgRemoteClientAppStatus_AppUpdateInfo) ProtoMessage()    {}

const Default_CMsgRemoteClientAppStatus_AppUpdateInfo_EstimatedSecondsRemaining int32 = -1

func (m *CMsgRemoteClientAppStatus_AppUpdateInfo) GetTimeUpdateStart() uint32 {
	if m != nil && m.TimeUpdateStart != nil {
		return *m.TimeUpdateStart
	}
	return 0
}

func (m *CMsgRemoteClientAppStatus_AppUpdateInfo) GetBytesToDownload() uint64 {
	if m != nil && m.BytesToDownload != nil {
		return *m.BytesToDownload
	}
	return 0
}

func (m *CMsgRemoteClientAppStatus_AppUpdateInfo) GetBytesDownloaded() uint64 {
	if m != nil && m.BytesDownloaded != nil {
		return *m.BytesDownloaded
	}
	return 0
}

func (m *CMsgRemoteClientAppStatus_AppUpdateInfo) GetBytesToProcess() uint64 {
	if m != nil && m.BytesToProcess != nil {
		return *m.BytesToProcess
	}
	return 0
}

func (m *CMsgRemoteClientAppStatus_AppUpdateInfo) GetBytesProcessed() uint64 {
	if m != nil && m.BytesProcessed != nil {
		return *m.BytesProcessed
	}
	return 0
}

func (m *CMsgRemoteClientAppStatus_AppUpdateInfo) GetEstimatedSecondsRemaining() int32 {
	if m != nil && m.EstimatedSecondsRemaining != nil {
		return *m.EstimatedSecondsRemaining
	}
	return Default_CMsgRemoteClientAppStatus_AppUpdateInfo_EstimatedSecondsRemaining
}

func (m *CMsgRemoteClientAppStatus_AppUpdateInfo) GetUpdateResult() int32 {
	if m != nil && m.UpdateResult != nil {
		return *m.UpdateResult
	}
	return 0
}

type CMsgRemoteClientAppStatus_ShortcutInfo struct {
	Name             *string  `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Icon             *string  `protobuf:"bytes,2,opt,name=icon" json:"icon,omitempty"`
	Categories       []string `protobuf:"bytes,3,rep,name=categories" json:"categories,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *CMsgRemoteClientAppStatus_ShortcutInfo) Reset() {
	*m = CMsgRemoteClientAppStatus_ShortcutInfo{}
}
func (m *CMsgRemoteClientAppStatus_ShortcutInfo) String() string { return proto.CompactTextString(m) }
func (*CMsgRemoteClientAppStatus_ShortcutInfo) ProtoMessage()    {}

func (m *CMsgRemoteClientAppStatus_ShortcutInfo) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *CMsgRemoteClientAppStatus_ShortcutInfo) GetIcon() string {
	if m != nil && m.Icon != nil {
		return *m.Icon
	}
	return ""
}

func (m *CMsgRemoteClientAppStatus_ShortcutInfo) GetCategories() []string {
	if m != nil {
		return m.Categories
	}
	return nil
}

type CMsgRemoteClientAppStatus_AppStatus struct {
	AppId            *uint32                                  `protobuf:"varint,1,opt,name=app_id" json:"app_id,omitempty"`
	AppState         *uint32                                  `protobuf:"varint,2,opt,name=app_state" json:"app_state,omitempty"`
	UpdateInfo       *CMsgRemoteClientAppStatus_AppUpdateInfo `protobuf:"bytes,3,opt,name=update_info" json:"update_info,omitempty"`
	ShortcutInfo     *CMsgRemoteClientAppStatus_ShortcutInfo  `protobuf:"bytes,4,opt,name=shortcut_info" json:"shortcut_info,omitempty"`
	XXX_unrecognized []byte                                   `json:"-"`
}

func (m *CMsgRemoteClientAppStatus_AppStatus) Reset()         { *m = CMsgRemoteClientAppStatus_AppStatus{} }
func (m *CMsgRemoteClientAppStatus_AppStatus) String() string { return proto.CompactTextString(m) }
func (*CMsgRemoteClientAppStatus_AppStatus) ProtoMessage()    {}

func (m *CMsgRemoteClientAppStatus_AppStatus) GetAppId() uint32 {
	if m != nil && m.AppId != nil {
		return *m.AppId
	}
	return 0
}

func (m *CMsgRemoteClientAppStatus_AppStatus) GetAppState() uint32 {
	if m != nil && m.AppState != nil {
		return *m.AppState
	}
	return 0
}

func (m *CMsgRemoteClientAppStatus_AppStatus) GetUpdateInfo() *CMsgRemoteClientAppStatus_AppUpdateInfo {
	if m != nil {
		return m.UpdateInfo
	}
	return nil
}

func (m *CMsgRemoteClientAppStatus_AppStatus) GetShortcutInfo() *CMsgRemoteClientAppStatus_ShortcutInfo {
	if m != nil {
		return m.ShortcutInfo
	}
	return nil
}

type CMsgRemoteClientAuth struct {
	ClientId         *uint64                          `protobuf:"varint,1,opt,name=client_id" json:"client_id,omitempty"`
	Status           *CMsgRemoteClientBroadcastStatus `protobuf:"bytes,2,opt,name=status" json:"status,omitempty"`
	XXX_unrecognized []byte                           `json:"-"`
}

func (m *CMsgRemoteClientAuth) Reset()         { *m = CMsgRemoteClientAuth{} }
func (m *CMsgRemoteClientAuth) String() string { return proto.CompactTextString(m) }
func (*CMsgRemoteClientAuth) ProtoMessage()    {}

func (m *CMsgRemoteClientAuth) GetClientId() uint64 {
	if m != nil && m.ClientId != nil {
		return *m.ClientId
	}
	return 0
}

func (m *CMsgRemoteClientAuth) GetStatus() *CMsgRemoteClientBroadcastStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type CMsgRemoteClientAuthResponse struct {
	Eresult          *int32 `protobuf:"varint,1,opt,name=eresult,def=2" json:"eresult,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CMsgRemoteClientAuthResponse) Reset()         { *m = CMsgRemoteClientAuthResponse{} }
func (m *CMsgRemoteClientAuthResponse) String() string { return proto.CompactTextString(m) }
func (*CMsgRemoteClientAuthResponse) ProtoMessage()    {}

const Default_CMsgRemoteClientAuthResponse_Eresult int32 = 2

func (m *CMsgRemoteClientAuthResponse) GetEresult() int32 {
	if m != nil && m.Eresult != nil {
		return *m.Eresult
	}
	return Default_CMsgRemoteClientAuthResponse_Eresult
}

type CMsgRemoteClientStartStream struct {
	AppId              *uint32 `protobuf:"varint,1,opt,name=app_id" json:"app_id,omitempty"`
	Environment        *int32  `protobuf:"varint,2,opt,name=environment" json:"environment,omitempty"`
	HasGamepad         *bool   `protobuf:"varint,3,opt,name=has_gamepad" json:"has_gamepad,omitempty"`
	LaunchOption       *int32  `protobuf:"varint,4,opt,name=launch_option,def=-1" json:"launch_option,omitempty"`
	LockParentalLock   *bool   `protobuf:"varint,5,opt,name=lock_parental_lock,def=0" json:"lock_parental_lock,omitempty"`
	UnlockParentalLock *string `protobuf:"bytes,6,opt,name=unlock_parental_lock" json:"unlock_parental_lock,omitempty"`
	MaximumResolutionX *int32  `protobuf:"varint,7,opt,name=maximum_resolution_x" json:"maximum_resolution_x,omitempty"`
	MaximumResolutionY *int32  `protobuf:"varint,8,opt,name=maximum_resolution_y" json:"maximum_resolution_y,omitempty"`
	GamepadCount       *int32  `protobuf:"varint,9,opt,name=gamepad_count" json:"gamepad_count,omitempty"`
	XXX_unrecognized   []byte  `json:"-"`
}

func (m *CMsgRemoteClientStartStream) Reset()         { *m = CMsgRemoteClientStartStream{} }
func (m *CMsgRemoteClientStartStream) String() string { return proto.CompactTextString(m) }
func (*CMsgRemoteClientStartStream) ProtoMessage()    {}

const Default_CMsgRemoteClientStartStream_LaunchOption int32 = -1
const Default_CMsgRemoteClientStartStream_LockParentalLock bool = false

func (m *CMsgRemoteClientStartStream) GetAppId() uint32 {
	if m != nil && m.AppId != nil {
		return *m.AppId
	}
	return 0
}

func (m *CMsgRemoteClientStartStream) GetEnvironment() int32 {
	if m != nil && m.Environment != nil {
		return *m.Environment
	}
	return 0
}

func (m *CMsgRemoteClientStartStream) GetHasGamepad() bool {
	if m != nil && m.HasGamepad != nil {
		return *m.HasGamepad
	}
	return false
}

func (m *CMsgRemoteClientStartStream) GetLaunchOption() int32 {
	if m != nil && m.LaunchOption != nil {
		return *m.LaunchOption
	}
	return Default_CMsgRemoteClientStartStream_LaunchOption
}

func (m *CMsgRemoteClientStartStream) GetLockParentalLock() bool {
	if m != nil && m.LockParentalLock != nil {
		return *m.LockParentalLock
	}
	return Default_CMsgRemoteClientStartStream_LockParentalLock
}

func (m *CMsgRemoteClientStartStream) GetUnlockParentalLock() string {
	if m != nil && m.UnlockParentalLock != nil {
		return *m.UnlockParentalLock
	}
	return ""
}

func (m *CMsgRemoteClientStartStream) GetMaximumResolutionX() int32 {
	if m != nil && m.MaximumResolutionX != nil {
		return *m.MaximumResolutionX
	}
	return 0
}

func (m *CMsgRemoteClientStartStream) GetMaximumResolutionY() int32 {
	if m != nil && m.MaximumResolutionY != nil {
		return *m.MaximumResolutionY
	}
	return 0
}

func (m *CMsgRemoteClientStartStream) GetGamepadCount() int32 {
	if m != nil && m.GamepadCount != nil {
		return *m.GamepadCount
	}
	return 0
}

type CMsgRemoteClientStartStreamResponse struct {
	ELaunchResult    *int32  `protobuf:"varint,1,opt,name=e_launch_result,def=2" json:"e_launch_result,omitempty"`
	StreamPort       *uint32 `protobuf:"varint,2,opt,name=stream_port" json:"stream_port,omitempty"`
	LaunchOptions    []int32 `protobuf:"varint,3,rep,name=launch_options" json:"launch_options,omitempty"`
	AuthToken        []byte  `protobuf:"bytes,4,opt,name=auth_token" json:"auth_token,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CMsgRemoteClientStartStreamResponse) Reset()         { *m = CMsgRemoteClientStartStreamResponse{} }
func (m *CMsgRemoteClientStartStreamResponse) String() string { return proto.CompactTextString(m) }
func (*CMsgRemoteClientStartStreamResponse) ProtoMessage()    {}

const Default_CMsgRemoteClientStartStreamResponse_ELaunchResult int32 = 2

func (m *CMsgRemoteClientStartStreamResponse) GetELaunchResult() int32 {
	if m != nil && m.ELaunchResult != nil {
		return *m.ELaunchResult
	}
	return Default_CMsgRemoteClientStartStreamResponse_ELaunchResult
}

func (m *CMsgRemoteClientStartStreamResponse) GetStreamPort() uint32 {
	if m != nil && m.StreamPort != nil {
		return *m.StreamPort
	}
	return 0
}

func (m *CMsgRemoteClientStartStreamResponse) GetLaunchOptions() []int32 {
	if m != nil {
		return m.LaunchOptions
	}
	return nil
}

func (m *CMsgRemoteClientStartStreamResponse) GetAuthToken() []byte {
	if m != nil {
		return m.AuthToken
	}
	return nil
}

type CMsgRemoteClientPing struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *CMsgRemoteClientPing) Reset()         { *m = CMsgRemoteClientPing{} }
func (m *CMsgRemoteClientPing) String() string { return proto.CompactTextString(m) }
func (*CMsgRemoteClientPing) ProtoMessage()    {}

type CMsgRemoteClientPingResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *CMsgRemoteClientPingResponse) Reset()         { *m = CMsgRemoteClientPingResponse{} }
func (m *CMsgRemoteClientPingResponse) String() string { return proto.CompactTextString(m) }
func (*CMsgRemoteClientPingResponse) ProtoMessage()    {}

type CMsgRemoteClientAcceptEULA struct {
	AppId            []uint32 `protobuf:"varint,1,rep,name=app_id" json:"app_id,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *CMsgRemoteClientAcceptEULA) Reset()         { *m = CMsgRemoteClientAcceptEULA{} }
func (m *CMsgRemoteClientAcceptEULA) String() string { return proto.CompactTextString(m) }
func (*CMsgRemoteClientAcceptEULA) ProtoMessage()    {}

func (m *CMsgRemoteClientAcceptEULA) GetAppId() []uint32 {
	if m != nil {
		return m.AppId
	}
	return nil
}

type CMsgRemoteClientGetControllerConfig struct {
	AppId            *uint32 `protobuf:"varint,1,opt,name=app_id" json:"app_id,omitempty"`
	WindowType       *int32  `protobuf:"varint,2,opt,name=window_type" json:"window_type,omitempty"`
	ControllerIndex  *uint32 `protobuf:"varint,3,opt,name=controller_index" json:"controller_index,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CMsgRemoteClientGetControllerConfig) Reset()         { *m = CMsgRemoteClientGetControllerConfig{} }
func (m *CMsgRemoteClientGetControllerConfig) String() string { return proto.CompactTextString(m) }
func (*CMsgRemoteClientGetControllerConfig) ProtoMessage()    {}

func (m *CMsgRemoteClientGetControllerConfig) GetAppId() uint32 {
	if m != nil && m.AppId != nil {
		return *m.AppId
	}
	return 0
}

func (m *CMsgRemoteClientGetControllerConfig) GetWindowType() int32 {
	if m != nil && m.WindowType != nil {
		return *m.WindowType
	}
	return 0
}

func (m *CMsgRemoteClientGetControllerConfig) GetControllerIndex() uint32 {
	if m != nil && m.ControllerIndex != nil {
		return *m.ControllerIndex
	}
	return 0
}

type CMsgRemoteClientGetControllerConfigResponse struct {
	Eresult          *int32 `protobuf:"varint,1,opt,name=eresult,def=2" json:"eresult,omitempty"`
	ConfigVdf        []byte `protobuf:"bytes,2,opt,name=config_vdf" json:"config_vdf,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CMsgRemoteClientGetControllerConfigResponse) Reset() {
	*m = CMsgRemoteClientGetControllerConfigResponse{}
}
func (m *CMsgRemoteClientGetControllerConfigResponse) String() string {
	return proto.CompactTextString(m)
}
func (*CMsgRemoteClientGetControllerConfigResponse) ProtoMessage() {}

const Default_CMsgRemoteClientGetControllerConfigResponse_Eresult int32 = 2

func (m *CMsgRemoteClientGetControllerConfigResponse) GetEresult() int32 {
	if m != nil && m.Eresult != nil {
		return *m.Eresult
	}
	return Default_CMsgRemoteClientGetControllerConfigResponse_Eresult
}

func (m *CMsgRemoteClientGetControllerConfigResponse) GetConfigVdf() []byte {
	if m != nil {
		return m.ConfigVdf
	}
	return nil
}

func init() {
	proto.RegisterEnum("ERemoteClientBroadcastMsg", ERemoteClientBroadcastMsg_name, ERemoteClientBroadcastMsg_value)
	proto.RegisterEnum("ERemoteClientService", ERemoteClientService_name, ERemoteClientService_value)
}
